"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es" | "fr" | "pt" | "ar" | "zh" | "hi" | "bn" | "ru" | "ur"

interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

const translations: Translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    clients: "Clients",
    calendar: "Calendar",
    workouts: "Session Plans",
    programs: "Programs",
    exercises: "Drills & Activities",
    payments: "Payments",
    analytics: "Analytics",
    reports: "Reports",
    reminders: "Reminders",
    marketing: "Marketing",
    social: "Social",
    messages: "Messages",
    settings: "Settings",
    billing: "Billing",
    referrals: "Referrals",
    gia: "GIA",
    aiPersona: "AI Persona",
    trainingPlans: "Training Plans",
    conflicts: "Conflicts",
    // Common
    search: "Search",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    create: "Create",
    view: "View",
    loading: "Loading",
    submit: "Submit",
    continue: "Continue",
    back: "Back",
    next: "Next",
    done: "Done",
    close: "Close",
    confirm: "Confirm",
    // Dashboard
    welcomeBack: "Welcome back",
    totalClients: "Total Clients",
    activeSessions: "Active Sessions",
    monthlyRevenue: "Monthly Revenue",
    upcomingSession: "Upcoming Session",
  },
  es: {
    // Navigation
    dashboard: "Tablero",
    clients: "Clientes",
    calendar: "Calendario",
    workouts: "Planes de Sesión",
    programs: "Programas",
    exercises: "Ejercicios y Actividades",
    payments: "Pagos",
    analytics: "Análisis",
    reports: "Informes",
    reminders: "Recordatorios",
    marketing: "Marketing",
    social: "Social",
    messages: "Mensajes",
    settings: "Configuración",
    billing: "Facturación",
    referrals: "Referencias",
    gia: "GIA",
    aiPersona: "Persona IA",
    trainingPlans: "Planes de Entrenamiento",
    conflicts: "Conflictos",
    // Common
    search: "Buscar",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Agregar",
    create: "Crear",
    view: "Ver",
    loading: "Cargando",
    submit: "Enviar",
    continue: "Continuar",
    back: "Atrás",
    next: "Siguiente",
    done: "Hecho",
    close: "Cerrar",
    confirm: "Confirmar",
    // Dashboard
    welcomeBack: "Bienvenido de nuevo",
    totalClients: "Total de Clientes",
    activeSessions: "Sesiones Activas",
    monthlyRevenue: "Ingresos Mensuales",
    upcomingSession: "Próxima Sesión",
  },
  fr: {
    // Navigation
    dashboard: "Tableau de bord",
    clients: "Clients",
    calendar: "Calendrier",
    workouts: "Plans de Session",
    programs: "Programmes",
    exercises: "Exercices et Activités",
    payments: "Paiements",
    analytics: "Analytique",
    reports: "Rapports",
    reminders: "Rappels",
    marketing: "Marketing",
    social: "Social",
    messages: "Messages",
    settings: "Paramètres",
    billing: "Facturation",
    referrals: "Références",
    gia: "GIA",
    aiPersona: "Persona IA",
    trainingPlans: "Plans d'Entraînement",
    conflicts: "Conflits",
    // Common
    search: "Rechercher",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    create: "Créer",
    view: "Voir",
    loading: "Chargement",
    submit: "Soumettre",
    continue: "Continuer",
    back: "Retour",
    next: "Suivant",
    done: "Terminé",
    close: "Fermer",
    confirm: "Confirmer",
    // Dashboard
    welcomeBack: "Bienvenue",
    totalClients: "Total des Clients",
    activeSessions: "Sessions Actives",
    monthlyRevenue: "Revenu Mensuel",
    upcomingSession: "Prochaine Session",
  },
  pt: {
    // Navigation
    dashboard: "Painel",
    clients: "Clientes",
    calendar: "Calendário",
    workouts: "Planos de Sessão",
    programs: "Programas",
    exercises: "Exercícios e Atividades",
    payments: "Pagamentos",
    analytics: "Análises",
    reports: "Relatórios",
    reminders: "Lembretes",
    marketing: "Marketing",
    social: "Social",
    messages: "Mensagens",
    settings: "Configurações",
    billing: "Faturamento",
    referrals: "Referências",
    gia: "GIA",
    aiPersona: "Persona IA",
    trainingPlans: "Planos de Treino",
    conflicts: "Conflitos",
    // Common
    search: "Pesquisar",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    create: "Criar",
    view: "Ver",
    loading: "Carregando",
    submit: "Enviar",
    continue: "Continuar",
    back: "Voltar",
    next: "Próximo",
    done: "Concluído",
    close: "Fechar",
    confirm: "Confirmar",
    // Dashboard
    welcomeBack: "Bem-vindo de volta",
    totalClients: "Total de Clientes",
    activeSessions: "Sessões Ativas",
    monthlyRevenue: "Receita Mensal",
    upcomingSession: "Próxima Sessão",
  },
  ar: {
    // Navigation
    dashboard: "لوحة القيادة",
    clients: "العملاء",
    calendar: "التقويم",
    workouts: "التمارين",
    programs: "البرامج",
    exercises: "التمارين",
    payments: "المدفوعات",
    analytics: "التحليلات",
    reports: "التقارير",
    reminders: "التذكيرات",
    marketing: "التسويق",
    social: "اجتماعي",
    messages: "الرسائل",
    settings: "الإعدادات",
    billing: "الفواتير",
    referrals: "الإحالات",
    gia: "جيا",
    aiPersona: "شخصية الذكاء الاصطناعي",
    trainingPlans: "خطط التدريب",
    conflicts: "النزاعات",
    // Common
    search: "بحث",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    create: "إنشاء",
    view: "عرض",
    loading: "جار التحميل",
    submit: "إرسال",
    continue: "متابعة",
    back: "رجوع",
    next: "التالي",
    done: "تم",
    close: "إغلاق",
    confirm: "تأكيد",
    // Dashboard
    welcomeBack: "مرحبا بعودتك",
    totalClients: "إجمالي العملاء",
    activeSessions: "الجلسات النشطة",
    monthlyRevenue: "الإيرادات الشهرية",
    upcomingSession: "الجلسة القادمة",
  },
  zh: {
    // Navigation
    dashboard: "仪表板",
    clients: "客户",
    calendar: "日历",
    workouts: "锻炼",
    programs: "程序",
    exercises: "练习",
    payments: "付款",
    analytics: "分析",
    reports: "报告",
    reminders: "提醒",
    marketing: "营销",
    social: "社交",
    messages: "消息",
    settings: "设置",
    billing: "账单",
    referrals: "推荐",
    gia: "GIA",
    aiPersona: "AI角色",
    trainingPlans: "训练计划",
    conflicts: "冲突",
    // Common
    search: "搜索",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    create: "创建",
    view: "查看",
    loading: "加载中",
    submit: "提交",
    continue: "继续",
    back: "返回",
    next: "下一步",
    done: "完成",
    close: "关闭",
    confirm: "确认",
    // Dashboard
    welcomeBack: "欢迎回来",
    totalClients: "总客户数",
    activeSessions: "活跃会话",
    monthlyRevenue: "月收入",
    upcomingSession: "即将到来的会话",
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    clients: "ग्राहक",
    calendar: "कैलेंडर",
    workouts: "वर्कआउट",
    programs: "कार्यक्रम",
    exercises: "व्यायाम",
    payments: "भुगतान",
    analytics: "विश्लेषण",
    reports: "रिपोर्ट",
    reminders: "रिमाइंडर",
    marketing: "मार्केटिंग",
    social: "सामाजिक",
    messages: "संदेश",
    settings: "सेटिंग्स",
    billing: "बिलिंग",
    referrals: "रेफरल",
    gia: "जीआईए",
    aiPersona: "एआई व्यक्तित्व",
    trainingPlans: "प्रशिक्षण योजनाएं",
    conflicts: "संघर्ष",
    // Common
    search: "खोजें",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",
    create: "बनाएं",
    view: "देखें",
    loading: "लोड हो रहा है",
    submit: "जमा करें",
    continue: "जारी रखें",
    back: "वापस",
    next: "अगला",
    done: "हो गया",
    close: "बंद करें",
    confirm: "पुष्टि करें",
    // Dashboard
    welcomeBack: "वापसी पर स्वागत है",
    totalClients: "कुल ग्राहक",
    activeSessions: "सक्रिय सत्र",
    monthlyRevenue: "मासिक राजस्व",
    upcomingSession: "आगामी सत्र",
  },
  bn: {
    // Navigation
    dashboard: "ড্যাশবোর্ড",
    clients: "ক্লায়েন্ট",
    calendar: "ক্যালেন্ডার",
    workouts: "ওয়ার্কআউট",
    programs: "প্রোগ্রাম",
    exercises: "ব্যায়াম",
    payments: "পেমেন্ট",
    analytics: "বিশ্লেষণ",
    reports: "রিপোর্ট",
    reminders: "রিমাইন্ডার",
    marketing: "মার্কেটিং",
    social: "সামাজিক",
    messages: "বার্তা",
    settings: "সেটিংস",
    billing: "বিলিং",
    referrals: "রেফারেল",
    gia: "জিআইএ",
    aiPersona: "এআই ব্যক্তিত্ব",
    trainingPlans: "প্রশিক্ষণ পরিকল্পনা",
    conflicts: "দ্বন্দ্ব",
    // Common
    search: "অনুসন্ধান",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    add: "যোগ করুন",
    create: "তৈরি করুন",
    view: "দেখুন",
    loading: "লোড হচ্ছে",
    submit: "জমা দিন",
    continue: "চালিয়ে যান",
    back: "পিছনে",
    next: "পরবর্তী",
    done: "সম্পন্ন",
    close: "বন্ধ করুন",
    confirm: "নিশ্চিত করুন",
    // Dashboard
    welcomeBack: "ফিরে আসার স্বাগতম",
    totalClients: "মোট ক্লায়েন্ট",
    activeSessions: "সক্রিয় সেশন",
    monthlyRevenue: "মাসিক আয়",
    upcomingSession: "আসন্ন সেশন",
  },
  ru: {
    // Navigation
    dashboard: "Панель управления",
    clients: "Клиенты",
    calendar: "Календарь",
    workouts: "Тренировки",
    programs: "Программы",
    exercises: "Упражнения",
    payments: "Платежи",
    analytics: "Аналитика",
    reports: "Отчеты",
    reminders: "Напоминания",
    marketing: "Маркетинг",
    social: "Социальные сети",
    messages: "Сообщения",
    settings: "Настройки",
    billing: "Биллинг",
    referrals: "Рефералы",
    gia: "ГИА",
    aiPersona: "ИИ Персона",
    trainingPlans: "Планы тренировок",
    conflicts: "Конфликты",
    // Common
    search: "Поиск",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    add: "Добавить",
    create: "Создать",
    view: "Просмотр",
    loading: "Загрузка",
    submit: "Отправить",
    continue: "Продолжить",
    back: "Назад",
    next: "Далее",
    done: "Готово",
    close: "Закрыть",
    confirm: "Подтвердить",
    // Dashboard
    welcomeBack: "С возвращением",
    totalClients: "Всего клиентов",
    activeSessions: "Активные сессии",
    monthlyRevenue: "Месячный доход",
    upcomingSession: "Предстоящая сессия",
  },
  ur: {
    // Navigation
    dashboard: "ڈیش بورڈ",
    clients: "کلائنٹس",
    calendar: "کیلنڈر",
    workouts: "ورک آؤٹس",
    programs: "پروگرامز",
    exercises: "مشقیں",
    payments: "ادائیگیاں",
    analytics: "تجزیات",
    reports: "رپورٹیں",
    reminders: "یاد دہانیاں",
    marketing: "مارکیٹنگ",
    social: "سماجی",
    messages: "پیغامات",
    settings: "ترتیبات",
    billing: "بلنگ",
    referrals: "حوالہ جات",
    gia: "جی آئی اے",
    aiPersona: "اے آئی شخصیت",
    trainingPlans: "تربیتی منصوبے",
    conflicts: "تنازعات",
    // Common
    search: "تلاش کریں",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    delete: "حذف کریں",
    edit: "ترمیم کریں",
    add: "شامل کریں",
    create: "بنائیں",
    view: "دیکھیں",
    loading: "لوڈ ہو رہا ہے",
    submit: "جمع کرائیں",
    continue: "جاری رکھیں",
    back: "واپس",
    next: "اگلا",
    done: "مکمل",
    close: "بند کریں",
    confirm: "تصدیق کریں",
    // Dashboard
    welcomeBack: "خوش آمدید",
    totalClients: "کل کلائنٹس",
    activeSessions: "فعال سیشنز",
    monthlyRevenue: "ماہانہ آمدنی",
    upcomingSession: "آنے والا سیشن",
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("preferred_language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("preferred_language", lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
