import { prisma } from "@/lib/prisma"

/**
 * Execute tool calls generated by GIA
 */
export async function executeToolCall(
    toolName: string,
    args: any,
    trainerId: string
) {
    console.log(`[GIA Agent] Executing tool: ${toolName}`, args)

    try {
        switch (toolName) {
            case 'update_client_profile':
                return await updateClientProfile(args, trainerId)

            case 'create_client':
                return await createClient(args, trainerId)

            case 'get_client_details':
                return await getClientDetails(args, trainerId)

            default:
                return { error: `Unknown tool: ${toolName}` }
        }
    } catch (error: any) {
        console.error(`[GIA Agent] Tool execution failed:`, error)
        return { error: `Tool execution failed: ${error.message}` }
    }
}

async function updateClientProfile(args: any, trainerId: string) {
    const { clientId, updates } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found or you don't have permission to modify them." }
    }

    // Perform update
    const updatedClient = await prisma.clients.update({
        where: { id: clientId },
        data: {
            ...updates,
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Updated profile for ${updatedClient.name}`,
        updatedFields: Object.keys(updates),
        client: {
            name: updatedClient.name,
            goals: updatedClient.goals,
            injuries: updatedClient.injuries,
            notes: updatedClient.notes
        }
    }
}

async function createClient(args: any, trainerId: string) {
    const { name, email, sport, notes } = args

    // Check for duplicate email if provided
    if (email) {
        const existing = await prisma.clients.findFirst({
            where: { trainerId, email }
        })
        if (existing) {
            return { error: `A client with email ${email} already exists.` }
        }
    }

    const newClient = await prisma.clients.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            name,
            email: email || `placeholder-${Date.now()}@example.com`, // Placeholder if not provided
            sport: sport || 'General Fitness',
            notes: notes || 'Added via GIA Chat',
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Created new client: ${newClient.name}`,
        client: newClient
    }
}

async function getClientDetails(args: any, trainerId: string) {
    const { clientId } = args

    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId },
        include: {
            payments: {
                take: 5,
                orderBy: { createdAt: 'desc' }
            },
            trainer_sessions: {
                take: 5,
                orderBy: { scheduledAt: 'desc' }
            }
        }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    return {
        success: true,
        client: {
            ...client,
            recentPayments: client.payments,
            recentSessions: client.trainer_sessions
        }
    }
}
