import { prisma } from "@/lib/prisma"

/**
 * Execute tool calls generated by GIA
 */
export async function executeToolCall(
    toolName: string,
    args: any,
    trainerId: string
) {
    console.log(`[GIA Agent] Executing tool: ${toolName}`, args)

    try {
        switch (toolName) {
            case 'update_client_profile':
                return await updateClientProfile(args, trainerId)

            case 'create_client':
                return await createClient(args, trainerId)

            case 'get_client_details':
                return await getClientDetails(args, trainerId)

            case 'schedule_session':
                return await scheduleSession(args, trainerId)

            case 'record_payment':
                return await recordPayment(args, trainerId)

            case 'save_program':
                return await saveProgram(args, trainerId)

            case 'get_upcoming_sessions':
                return await getUpcomingSessions(args, trainerId)

            default:
                return { error: `Unknown tool: ${toolName}` }
        }
    } catch (error: any) {
        console.error(`[GIA Agent] Tool execution failed:`, error)
        return { error: `Tool execution failed: ${error.message}` }
    }
}

async function updateClientProfile(args: any, trainerId: string) {
    const { clientId, updates } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found or you don't have permission to modify them." }
    }

    // Perform update
    const updatedClient = await prisma.clients.update({
        where: { id: clientId },
        data: {
            ...updates,
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Updated profile for ${updatedClient.name}`,
        updatedFields: Object.keys(updates),
        client: {
            name: updatedClient.name,
            goals: updatedClient.goals,
            injuries: updatedClient.injuries,
            notes: updatedClient.notes
        }
    }
}

async function createClient(args: any, trainerId: string) {
    const { name, email, sport, notes } = args

    // Check for duplicate email if provided
    if (email) {
        const existing = await prisma.clients.findFirst({
            where: { trainerId, email }
        })
        if (existing) {
            return { error: `A client with email ${email} already exists.` }
        }
    }

    const newClient = await prisma.clients.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            name,
            email: email || `placeholder-${Date.now()}@example.com`, // Placeholder if not provided
            sport: sport || 'General Fitness',
            notes: notes || 'Added via GIA Chat',
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Created new client: ${newClient.name}`,
        client: newClient
    }
}

async function getClientDetails(args: any, trainerId: string) {
    const { clientId } = args

    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId },
        include: {
            payments: {
                take: 5,
                orderBy: { createdAt: 'desc' }
            },
            trainer_sessions: {
                take: 5,
                orderBy: { scheduledAt: 'desc' }
            }
        }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    return {
        success: true,
        client: {
            ...client,
            recentPayments: client.payments,
            recentSessions: client.trainer_sessions
        }
    }
}

async function scheduleSession(args: any, trainerId: string) {
    const { clientId, scheduledAt, durationMinutes = 60, title, notes } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found or you don't have permission to schedule with them." }
    }

    const session = await prisma.trainer_sessions.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            clientId,
            appClientId: null,
            title,
            type: 'PERSONAL_TRAINING', // Default session type
            scheduledAt: new Date(scheduledAt),
            duration: durationMinutes,
            status: 'SCHEDULED',
            notes: notes || null,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Scheduled ${title} with ${client.name} for ${new Date(scheduledAt).toLocaleString()}`,
        session: {
            id: session.id,
            title: session.title,
            scheduledAt: session.scheduledAt,
            duration: session.duration,
            clientName: client.name
        }
    }
}

async function recordPayment(args: any, trainerId: string) {
    const { clientId, amount, method, sessionId, notes } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    const payment = await prisma.payments.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            clientId,
            sessionId: sessionId || null,
            amount,
            currency: 'USD',
            method,
            status: 'COMPLETED',
            description: notes || `Payment from ${client.name}`,
            paidAt: new Date(),
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Recorded $${amount} payment from ${client.name}`,
        payment: {
            id: payment.id,
            amount: payment.amount,
            method: payment.method,
            paidAt: payment.paidAt
        }
    }
}

async function saveProgram(args: any, trainerId: string) {
    const { title, description, content, programType, sportCategory, difficultyLevel, durationMinutes } = args

    const program = await prisma.gia_programs.create({
        data: {
            id: crypto.randomUUID(),
            instructorId: trainerId,
            title,
            description: description || null,
            content,
            type: programType,
            sportCategory: sportCategory || null,
            difficultyLevel: difficultyLevel || null,
            durationMinutes: durationMinutes || null,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Saved program: ${title}`,
        program: {
            id: program.id,
            title: program.title,
            programType: program.type
        }
    }
}

async function getUpcomingSessions(args: any, trainerId: string) {
    const { daysAhead = 7 } = args

    const now = new Date()
    const futureDate = new Date()
    futureDate.setDate(now.getDate() + daysAhead)

    const sessions = await prisma.trainer_sessions.findMany({
        where: {
            trainerId,
            scheduledAt: {
                gte: now,
                lte: futureDate
            },
            status: {
                not: 'CANCELLED'
            }
        },
        include: {
            clients: {
                select: {
                    name: true,
                    sport: true
                }
            }
        },
        orderBy: { scheduledAt: 'asc' },
        take: 20
    })

    return {
        success: true,
        message: `Found ${sessions.length} upcoming sessions in the next ${daysAhead} days`,
        sessions: sessions.map(s => ({
            id: s.id,
            title: s.title,
            scheduledAt: s.scheduledAt,
            duration: s.duration,
            clientName: s.clients?.name,
            status: s.status
        }))
    }
}
