import { prisma } from "@/lib/prisma"

/**
 * Execute tool calls generated by GIA
 */
export async function executeToolCall(
    toolName: string,
    args: any,
    trainerId: string
) {
    console.log(`[GIA Agent] Executing tool: ${toolName}`, args)

    try {
        switch (toolName) {
            case 'update_client_profile':
                return await updateClientProfile(args, trainerId)

            case 'create_client':
                return await createClient(args, trainerId)

            case 'get_client_details':
                return await getClientDetails(args, trainerId)

            case 'schedule_session':
                return await scheduleSession(args, trainerId)

            case 'record_payment':
                return await recordPayment(args, trainerId)

            case 'save_program':
                return await saveProgram(args, trainerId)

            case 'get_upcoming_sessions':
                return await getUpcomingSessions(args, trainerId)

            case 'create_invoice':
                return await createInvoice(args, trainerId)

            case 'assign_program_to_client':
                return await assignProgramToClient(args, trainerId)

            case 'cancel_session':
                return await cancelSession(args, trainerId)

            case 'get_client_analytics':
                return await getClientAnalytics(args, trainerId)

            case 'get_revenue_summary':
                return await getRevenueSummary(args, trainerId)

            case 'get_hot_leads':
                return await getHotLeads(args, trainerId)

            case 'get_churn_risk':
                return await getChurnRisk(args, trainerId)

            case 'generate_lead_outreach':
                return await generateLeadOutreachTool(args, trainerId)

            default:
                return { error: `Unknown tool: ${toolName}` }
        }
    } catch (error: any) {
        console.error(`[GIA Agent] Tool execution failed:`, error)
        return { error: `Tool execution failed: ${error.message}` }
    }
}

// ... existing functions ...

async function getHotLeads(args: any, trainerId: string) {
    const { minScore = 70 } = args

    // In a real app, this would query the DB. For now, we use the same mock data as the API
    // to ensure consistency across the demo.
    const mockLeads = [
        { id: 'lead-1', name: 'Jessica Chen', sport: 'Tennis', score: 95, notes: 'Looking for weight loss' },
        { id: 'lead-2', name: 'Marcus Williams', sport: 'Golf', score: 88, notes: 'Needs swing correction' },
        { id: 'lead-3', name: 'Sarah Johnson', sport: 'Pickleball', score: 82, notes: 'Beginner' },
        { id: 'lead-4', name: 'David Kim', sport: 'Basketball', score: 75, notes: 'Advanced skills training' }
    ]

    const hotLeads = mockLeads.filter(l => l.score >= minScore)

    return {
        success: true,
        message: `Found ${hotLeads.length} hot leads with score >= ${minScore}`,
        leads: hotLeads
    }
}

async function getChurnRisk(args: any, trainerId: string) {
    // Import dynamically to avoid circular dependencies if any
    const { analyzeClientRisk } = await import('@/lib/gia/intelligence')
    const risks = await analyzeClientRisk(trainerId)

    const highRisk = risks.filter(r => r.riskLevel === 'high')
    const mediumRisk = risks.filter(r => r.riskLevel === 'medium')

    return {
        success: true,
        message: `Analysis complete: ${highRisk.length} high risk, ${mediumRisk.length} medium risk clients.`,
        summary: {
            highRiskCount: highRisk.length,
            mediumRiskCount: mediumRisk.length,
            totalAnalyzed: risks.length
        },
        highRiskClients: highRisk.map(c => ({
            name: c.clientName,
            reason: c.reasons.join(', '),
            riskScore: c.riskScore
        }))
    }
}

async function generateLeadOutreachTool(args: any, trainerId: string) {
    const { leadId, tone = 'casual' } = args
    const { generateLeadOutreach } = await import('@/lib/gia/openai')
    const { prisma } = await import('@/lib/prisma')

    // Get trainer details
    const trainer = await prisma.users.findUnique({
        where: { id: trainerId },
        select: { name: true }
    })

    // Mock lead lookup (since we're using mock leads)
    const mockLeads = [
        { id: 'lead-1', name: 'Jessica Chen', sport: 'Tennis', experience: 'Beginner', goals: 'weight loss, endurance' },
        { id: 'lead-2', name: 'Marcus Williams', sport: 'Golf', experience: 'Intermediate', goals: 'fix slice, consistency' },
        { id: 'lead-3', name: 'Sarah Johnson', sport: 'Pickleball', experience: 'Beginner', goals: 'social, fitness' },
        { id: 'lead-4', name: 'David Kim', sport: 'Basketball', experience: 'Advanced', goals: 'skills, strength' }
    ]

    const lead = mockLeads.find(l => l.id === leadId)

    if (!lead) {
        return { error: "Lead not found" }
    }

    const message = await generateLeadOutreach({
        name: lead.name,
        goals: lead.goals,
        experience: lead.experience,
        sport: lead.sport,
        trainerName: trainer?.name || 'Trainer'
    })

    return {
        success: true,
        message: "Draft generated successfully",
        draft: message,
        leadName: lead.name
    }
}

// ... rest of file ...


async function updateClientProfile(args: any, trainerId: string) {
    const { clientId, updates } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found or you don't have permission to modify them." }
    }

    // Perform update
    const updatedClient = await prisma.clients.update({
        where: { id: clientId },
        data: {
            ...updates,
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Updated profile for ${updatedClient.name}`,
        updatedFields: Object.keys(updates),
        client: {
            name: updatedClient.name,
            goals: updatedClient.goals,
            injuries: updatedClient.injuries,
            notes: updatedClient.notes
        }
    }
}

async function createClient(args: any, trainerId: string) {
    const { name, email, sport, notes } = args

    // Check for duplicate email if provided
    if (email) {
        const existing = await prisma.clients.findFirst({
            where: { trainerId, email }
        })
        if (existing) {
            return { error: `A client with email ${email} already exists.` }
        }
    }

    const newClient = await prisma.clients.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            name,
            email: email || `placeholder-${Date.now()}@example.com`, // Placeholder if not provided
            sport: sport || 'General Fitness',
            notes: notes || 'Added via GIA Chat',
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Created new client: ${newClient.name}`,
        client: newClient
    }
}

async function getClientDetails(args: any, trainerId: string) {
    const { clientId } = args

    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId },
        include: {
            payments: {
                take: 5,
                orderBy: { createdAt: 'desc' }
            },
            trainer_sessions: {
                take: 5,
                orderBy: { scheduledAt: 'desc' }
            }
        }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    return {
        success: true,
        client: {
            ...client,
            recentPayments: client.payments,
            recentSessions: client.trainer_sessions
        }
    }
}

async function scheduleSession(args: any, trainerId: string) {
    const { clientId, scheduledAt, durationMinutes = 60, title, notes } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found or you don't have permission to schedule with them." }
    }

    const session = await prisma.trainer_sessions.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            clientId,
            appClientId: null,
            title,
            type: 'PERSONAL_TRAINING', // Default session type
            scheduledAt: new Date(scheduledAt),
            duration: durationMinutes,
            status: 'SCHEDULED',
            notes: notes || null,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Scheduled ${title} with ${client.name} for ${new Date(scheduledAt).toLocaleString()}`,
        session: {
            id: session.id,
            title: session.title,
            scheduledAt: session.scheduledAt,
            duration: session.duration,
            clientName: client.name
        }
    }
}

async function recordPayment(args: any, trainerId: string) {
    const { clientId, amount, method, sessionId, notes } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    const payment = await prisma.payments.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            clientId,
            sessionId: sessionId || null,
            amount,
            currency: 'USD',
            method,
            status: 'COMPLETED',
            description: notes || `Payment from ${client.name}`,
            paidAt: new Date(),
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Recorded $${amount} payment from ${client.name}`,
        payment: {
            id: payment.id,
            amount: payment.amount,
            method: payment.method,
            paidAt: payment.paidAt
        }
    }
}

async function saveProgram(args: any, trainerId: string) {
    const { title, description, content, programType, sportCategory, difficultyLevel, durationMinutes } = args

    const program = await prisma.gia_programs.create({
        data: {
            id: crypto.randomUUID(),
            instructorId: trainerId,
            title,
            description: description || null,
            content,
            type: programType,
            sportCategory: sportCategory || null,
            difficultyLevel: difficultyLevel || null,
            durationMinutes: durationMinutes || null,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Saved program: ${title}`,
        program: {
            id: program.id,
            title: program.title,
            programType: program.type
        }
    }
}

async function getUpcomingSessions(args: any, trainerId: string) {
    const { daysAhead = 7 } = args

    const now = new Date()
    const futureDate = new Date()
    futureDate.setDate(now.getDate() + daysAhead)

    const sessions = await prisma.trainer_sessions.findMany({
        where: {
            trainerId,
            scheduledAt: {
                gte: now,
                lte: futureDate
            },
            status: {
                not: 'CANCELLED'
            }
        },
        include: {
            clients: {
                select: {
                    name: true,
                    sport: true
                }
            }
        },
        orderBy: { scheduledAt: 'asc' },
        take: 20
    })

    return {
        success: true,
        message: `Found ${sessions.length} upcoming sessions in the next ${daysAhead} days`,
        sessions: sessions.map(s => ({
            id: s.id,
            title: s.title,
            scheduledAt: s.scheduledAt,
            duration: s.duration,
            clientName: s.clients?.name,
            status: s.status
        }))
    }
}

async function createInvoice(args: any, trainerId: string) {
    const { clientId, amount, dueDate, description } = args

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    const invoice = await prisma.payments.create({
        data: {
            id: crypto.randomUUID(),
            trainerId,
            clientId,
            amount,
            currency: 'USD',
            method: 'CARD', // Default method for invoices
            status: 'PENDING',
            description: description || `Invoice for ${client.name}`,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Created invoice for ${client.name}: $${amount}`,
        invoice: {
            id: invoice.id,
            amount: invoice.amount,
            status: invoice.status,
            clientName: client.name
        }
    }
}

async function assignProgramToClient(args: any, trainerId: string) {
    const { programId, clientId } = args

    // Verify program belongs to trainer
    const program = await prisma.gia_programs.findFirst({
        where: { id: programId, instructorId: trainerId }
    })

    if (!program) {
        return { error: "Program not found or you don't have permission." }
    }

    // Verify client belongs to trainer
    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    // Check if already assigned
    const existing = await prisma.gia_program_usage.findFirst({
        where: { programId, studentId: clientId }
    })

    if (existing) {
        return { error: `${program.title} is already assigned to ${client.name}` }
    }

    const assignment = await prisma.gia_program_usage.create({
        data: {
            id: crypto.randomUUID(),
            programId,
            instructorId: trainerId,
            studentId: clientId
        }
    })

    // Increment usage count
    await prisma.gia_programs.update({
        where: { id: programId },
        data: { timesUsed: { increment: 1 } }
    })

    return {
        success: true,
        message: `Assigned "${program.title}" to ${client.name}`,
        assignment: {
            id: assignment.id,
            programTitle: program.title,
            clientName: client.name
        }
    }
}

async function cancelSession(args: any, trainerId: string) {
    const { sessionId, reason } = args

    // Verify session belongs to trainer
    const session = await prisma.trainer_sessions.findFirst({
        where: { id: sessionId, trainerId },
        include: {
            clients: {
                select: { name: true }
            }
        }
    })

    if (!session) {
        return { error: "Session not found or you don't have permission." }
    }

    const updatedSession = await prisma.trainer_sessions.update({
        where: { id: sessionId },
        data: {
            status: 'CANCELLED',
            notes: reason ? `Cancelled: ${reason}` : 'Cancelled',
            updatedAt: new Date()
        }
    })

    return {
        success: true,
        message: `Cancelled session: ${session.title} with ${session.clients?.name}`,
        session: {
            id: updatedSession.id,
            title: updatedSession.title,
            status: updatedSession.status
        }
    }
}

async function getClientAnalytics(args: any, trainerId: string) {
    const { clientId } = args

    const client = await prisma.clients.findFirst({
        where: { id: clientId, trainerId },
        include: {
            payments: true,
            trainer_sessions: {
                where: { status: { not: 'CANCELLED' } }
            }
        }
    })

    if (!client) {
        return { error: "Client not found." }
    }

    const totalPaid = client.payments
        .filter(p => p.status === 'COMPLETED')
        .reduce((sum, p) => sum + p.amount, 0)

    const totalPending = client.payments
        .filter(p => p.status === 'PENDING')
        .reduce((sum, p) => sum + p.amount, 0)

    return {
        success: true,
        analytics: {
            clientName: client.name,
            totalSessions: client.trainer_sessions.length,
            completedSessions: client.trainer_sessions.filter(s => s.status === 'COMPLETED').length,
            upcomingSessions: client.trainer_sessions.filter(s => s.status === 'SCHEDULED').length,
            totalRevenue: totalPaid,
            pendingPayments: totalPending
        }
    }
}

async function getRevenueSummary(args: any, trainerId: string) {
    const { startDate, endDate } = args

    const where: any = { trainerId }

    if (startDate && endDate) {
        where.createdAt = {
            gte: new Date(startDate),
            lte: new Date(endDate)
        }
    }

    const payments = await prisma.payments.findMany({ where })

    const totalRevenue = payments
        .filter(p => p.status === 'COMPLETED')
        .reduce((sum, p) => sum + p.amount, 0)

    const pendingRevenue = payments
        .filter(p => p.status === 'PENDING')
        .reduce((sum, p) => sum + p.amount, 0)

    const completedCount = payments.filter(p => p.status === 'COMPLETED').length
    const pendingCount = payments.filter(p => p.status === 'PENDING').length

    return {
        success: true,
        summary: {
            totalRevenue,
            pendingRevenue,
            completedPayments: completedCount,
            pendingPayments: pendingCount,
            totalPayments: payments.length,
            period: startDate && endDate ? `${startDate} to ${endDate}` : 'All time'
        }
    }
}
