/**
 * Parse GIA responses to extract structured program data
 */

export interface ParsedProgram {
  title: string
  description?: string
  type: 'lesson_plan' | 'workout_program' | 'class_sequence' | 'drill_progression'
  sportCategory?: string
  difficultyLevel?: string
  durationMinutes?: number
  content: any
  canSave: boolean
}

export function parseGIAResponse(response: string, mode: string): ParsedProgram | null {
  // Check if response looks like a program/lesson plan
  const isProgramResponse = 
    response.includes('LESSON PLAN') ||
    response.includes('PROGRAM') ||
    response.includes('WORKOUT') ||
    response.includes('CLASS SEQUENCE') ||
    response.includes('DRILL PROGRESSION') ||
    response.includes('Week 1') ||
    response.includes('Day 1') ||
    response.includes('Session 1') ||
    (response.includes('**') && response.length > 500) // Structured long response

  if (!isProgramResponse) {
    return null
  }

  // Extract title
  let title = ''
  const titleMatch = response.match(/\*\*([A-Z][A-Z\s&-]+)\*\*/)
  if (titleMatch) {
    title = titleMatch[1].trim()
  } else {
    // Generate title from mode
    const modeMap: Record<string, string> = {
      wellness: 'Wellness Program',
      sports: 'Sports Lesson Plan',
      programming: 'Performance Program',
      nutrition: 'Nutrition Plan',
      rehab: 'Rehab Protocol'
    }
    title = modeMap[mode] || 'Training Program'
  }

  // Determine type
  let type: ParsedProgram['type'] = 'lesson_plan'
  if (response.includes('WORKOUT') || response.includes('STRENGTH') || response.includes('CONDITIONING')) {
    type = 'workout_program'
  } else if (response.includes('CLASS') || response.includes('SEQUENCE') || response.includes('FLOW')) {
    type = 'class_sequence'
  } else if (response.includes('DRILL') || response.includes('PROGRESSION')) {
    type = 'drill_progression'
  }

  // Extract duration
  let durationMinutes: number | undefined
  const durationMatch = response.match(/(\d+)\s*[-–]?\s*minute/i)
  if (durationMatch) {
    durationMinutes = parseInt(durationMatch[1])
  }

  // Extract difficulty
  let difficultyLevel: string | undefined
  if (response.toLowerCase().includes('beginner')) difficultyLevel = 'beginner'
  else if (response.toLowerCase().includes('intermediate')) difficultyLevel = 'intermediate'
  else if (response.toLowerCase().includes('advanced')) difficultyLevel = 'advanced'

  // Extract sport category from response
  let sportCategory: string | undefined
  const sports = [
    'pickleball', 'tennis', 'golf', 'basketball', 'soccer', 'volleyball',
    'yoga', 'pilates', 'barre', 'meditation', 'padel', 'racquetball'
  ]
  for (const sport of sports) {
    if (response.toLowerCase().includes(sport)) {
      sportCategory = sport
      break
    }
  }

  // Structure the content
  const content = {
    raw: response,
    sections: extractSections(response),
    metadata: {
      generatedAt: new Date().toISOString(),
      mode,
      wordCount: response.split(/\s+/).length
    }
  }

  return {
    title,
    description: `Generated by GIA in ${mode} mode`,
    type,
    sportCategory,
    difficultyLevel,
    durationMinutes,
    content,
    canSave: true
  }
}

function extractSections(text: string): Record<string, string> {
  const sections: Record<string, string> = {}
  
  // Split by common section headers
  const sectionRegex = /\*\*([A-Z][A-Z\s&:-]+)\*\*/g
  let lastIndex = 0
  let lastHeader = 'Introduction'
  
  let match
  while ((match = sectionRegex.exec(text)) !== null) {
    const header = match[1].trim()
    const sectionStart = match.index + match[0].length
    
    if (lastHeader) {
      sections[lastHeader] = text.substring(lastIndex, match.index).trim()
    }
    
    lastHeader = header
    lastIndex = sectionStart
  }
  
  // Add final section
  if (lastHeader) {
    sections[lastHeader] = text.substring(lastIndex).trim()
  }
  
  return sections
}

