/**
 * Demo Data for Pickleball Trainer - Kai
 * This provides realistic demo data for all dashboard pages
 */

export const demoTrainer = {
  name: 'Kai',
  email: 'kai@pickleballpro.com',
  fullName: 'Kai Anderson',
  businessName: 'Kai\'s Pickleball Academy',
  specialty: 'Pickleball',
  rating: 4.9,
  totalSessions: 342,
  bio: 'Professional pickleball instructor with 8+ years of experience. Specializing in doubles strategy and competitive play.',
  certifications: ['PPR Certified', 'IPTPA Level 3', 'USAPA Ambassador'],
  hourlyRate: 75,
  phone: '(555) 123-4567',
  location: 'San Diego, CA',
  isAvailable: true,
}

export const demoClients = [
  {
    id: '1',
    name: 'Sarah Martinez',
    email: 'sarah.m@email.com',
    phone: '(555) 234-5678',
    level: 'Intermediate',
    joinedDate: '2024-09-15',
    totalSessions: 24,
    lastSession: '2024-11-15',
    notes: 'Working on backhand volleys and court positioning',
    goals: 'Compete in local 3.5 tournaments',
  },
  {
    id: '2',
    name: 'Mike Thompson',
    email: 'mike.t@email.com',
    phone: '(555) 345-6789',
    level: 'Advanced',
    joinedDate: '2024-08-10',
    totalSessions: 38,
    lastSession: '2024-11-18',
    notes: 'Preparing for USAPA Nationals',
    goals: 'Move up to 4.5 skill level',
  },
  {
    id: '3',
    name: 'Jennifer Lee',
    email: 'jen.lee@email.com',
    phone: '(555) 456-7890',
    level: 'Beginner',
    joinedDate: '2024-10-20',
    totalSessions: 8,
    lastSession: '2024-11-17',
    notes: 'New to pickleball, great enthusiasm',
    goals: 'Master basic strokes and rules',
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david.p@email.com',
    phone: '(555) 567-8901',
    level: 'Intermediate',
    joinedDate: '2024-07-05',
    totalSessions: 45,
    lastSession: '2024-11-16',
    notes: 'Focuses on doubles strategy',
    goals: 'Win club championship',
  },
  {
    id: '5',
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 678-9012',
    level: 'Advanced',
    joinedDate: '2024-06-12',
    totalSessions: 52,
    lastSession: '2024-11-19',
    notes: 'Excellent court awareness, working on power shots',
    goals: 'Coach junior players',
  },
]

export const demoSessions = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Sarah Martinez',
    scheduledAt: new Date('2024-11-22T10:00:00'),
    duration: 60,
    type: 'Private Lesson',
    status: 'SCHEDULED',
    notes: 'Focus on serve consistency',
    location: 'Court 3',
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'Mike Thompson',
    scheduledAt: new Date('2024-11-22T14:00:00'),
    duration: 90,
    type: 'Advanced Training',
    status: 'SCHEDULED',
    notes: 'Tournament prep - singles strategy',
    location: 'Court 1',
  },
  {
    id: '3',
    clientId: '3',
    clientName: 'Jennifer Lee',
    scheduledAt: new Date('2024-11-23T09:00:00'),
    duration: 60,
    type: 'Beginner Lesson',
    status: 'SCHEDULED',
    notes: 'Introduction to dinking',
    location: 'Court 2',
  },
  {
    id: '4',
    clientId: '4',
    clientName: 'David Park',
    scheduledAt: new Date('2024-11-23T11:00:00'),
    duration: 60,
    type: 'Private Lesson',
    status: 'SCHEDULED',
    notes: 'Doubles positioning drills',
    location: 'Court 3',
  },
  {
    id: '5',
    clientId: '5',
    clientName: 'Emily Rodriguez',
    scheduledAt: new Date('2024-11-21T15:00:00'),
    duration: 60,
    type: 'Private Lesson',
    status: 'COMPLETED',
    notes: 'Overhead smash technique',
    location: 'Court 1',
  },
]

export const demoPayments = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Sarah Martinez',
    amount: 300,
    method: 'CREDIT_CARD',
    status: 'COMPLETED',
    description: '4-session package',
    createdAt: new Date('2024-11-15'),
    paidAt: new Date('2024-11-15'),
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'Mike Thompson',
    amount: 450,
    method: 'BANK_TRANSFER',
    status: 'COMPLETED',
    description: '6-session advanced training',
    createdAt: new Date('2024-11-10'),
    paidAt: new Date('2024-11-12'),
  },
  {
    id: '3',
    clientId: '3',
    clientName: 'Jennifer Lee',
    amount: 150,
    method: 'CASH',
    status: 'PENDING',
    description: '2-session beginner package',
    createdAt: new Date('2024-11-05'),
    paidAt: null,
  },
  {
    id: '4',
    clientId: '4',
    clientName: 'David Park',
    amount: 600,
    method: 'CREDIT_CARD',
    status: 'COMPLETED',
    description: 'Monthly unlimited package',
    createdAt: new Date('2024-11-01'),
    paidAt: new Date('2024-11-01'),
  },
]

export const demoExercises = [
  {
    id: '1',
    name: 'Dinking Drill',
    category: 'Fundamentals',
    description: 'Practice soft shots in the kitchen zone to improve touch and control',
    duration: 15,
    difficulty: 'Beginner',
    equipment: ['Pickleballs', 'Court'],
  },
  {
    id: '2',
    name: 'Third Shot Drop Practice',
    category: 'Advanced Technique',
    description: 'Master the essential third shot drop to get to the net',
    duration: 20,
    difficulty: 'Intermediate',
    equipment: ['Pickleballs', 'Cones', 'Court'],
  },
  {
    id: '3',
    name: 'Serve & Return Drill',
    category: 'Fundamentals',
    description: 'Improve serve accuracy and return consistency',
    duration: 15,
    difficulty: 'Beginner',
    equipment: ['Pickleballs', 'Targets'],
  },
  {
    id: '4',
    name: 'Attacking Drill',
    category: 'Offensive Strategy',
    description: 'Learn when and how to attack high balls effectively',
    duration: 25,
    difficulty: 'Advanced',
    equipment: ['Pickleballs', 'Court'],
  },
  {
    id: '5',
    name: 'Footwork Ladder',
    category: 'Conditioning',
    description: 'Improve court movement and positioning speed',
    duration: 10,
    difficulty: 'Intermediate',
    equipment: ['Agility ladder', 'Cones'],
  },
]

export const demoWorkouts = [
  {
    id: '1',
    name: 'Beginner Fundamentals Session',
    description: 'Introduction to basic pickleball strokes and rules',
    level: 'Beginner',
    duration: 60,
    exercises: ['Dinking Drill', 'Serve & Return Drill'],
    createdAt: new Date('2024-11-01'),
  },
  {
    id: '2',
    name: 'Intermediate Skills Development',
    description: 'Advancing technique with third shot drops and volleys',
    level: 'Intermediate',
    duration: 90,
    exercises: ['Third Shot Drop Practice', 'Footwork Ladder', 'Attacking Drill'],
    createdAt: new Date('2024-10-28'),
  },
  {
    id: '3',
    name: 'Tournament Prep - Doubles Strategy',
    description: 'Advanced doubles positioning and communication',
    level: 'Advanced',
    duration: 90,
    exercises: ['Attacking Drill', 'Third Shot Drop Practice'],
    createdAt: new Date('2024-11-05'),
  },
]

export const demoMessages = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Sarah Martinez',
    lastMessage: 'Can we reschedule Friday\'s session?',
    timestamp: new Date('2024-11-19T14:30:00'),
    unread: true,
    messages: [
      {
        id: 'm1',
        sender: 'client',
        content: 'Hi Kai! Great session today, really helped with my backhand.',
        timestamp: new Date('2024-11-19T10:30:00'),
      },
      {
        id: 'm2',
        sender: 'trainer',
        content: 'Thanks Sarah! Keep practicing that follow-through we worked on.',
        timestamp: new Date('2024-11-19T11:00:00'),
      },
      {
        id: 'm3',
        sender: 'client',
        content: 'Can we reschedule Friday\'s session?',
        timestamp: new Date('2024-11-19T14:30:00'),
      },
    ],
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'Mike Thompson',
    lastMessage: 'Looking forward to tomorrow\'s training!',
    timestamp: new Date('2024-11-18T19:00:00'),
    unread: false,
    messages: [
      {
        id: 'm4',
        sender: 'client',
        content: 'Looking forward to tomorrow\'s training!',
        timestamp: new Date('2024-11-18T19:00:00'),
      },
    ],
  },
]

export const demoReminders = [
  {
    id: '1',
    name: 'Session Reminder - 24h Before',
    type: 'email',
    trigger: '24h before session',
    active: true,
    message: 'Hi {client_name}, this is a reminder about your pickleball session tomorrow at {session_time} at {location}. See you on the court!',
    sentCount: 156,
  },
  {
    id: '2',
    name: 'Payment Due Reminder',
    type: 'sms',
    trigger: 'Payment overdue',
    active: true,
    message: 'Hi {client_name}, you have an outstanding payment of ${amount}. Please submit payment at your earliest convenience.',
    sentCount: 23,
  },
  {
    id: '3',
    name: 'Weekly Check-in',
    type: 'email',
    trigger: 'Weekly (Monday 9am)',
    active: false,
    message: 'Hi {client_name}, how is your pickleball training going? Any questions or adjustments needed?',
    sentCount: 89,
  },
]

export const demoDashboardStats = {
  trainer: demoTrainer,
  revenue: {
    thisMonth: 4850,
    lastMonth: 4200,
    change: 15.5,
    forecast: 5529,
    totalTransactions: 18,
  },
  clients: {
    total: 5,
    active: 5,
    inactive: 0,
    atRisk: 1,
    atRiskList: [
      {
        id: '3',
        name: 'Jennifer Lee',
        email: 'jen.lee@email.com',
        lastSession: new Date('2024-11-17'),
      },
    ],
    highEngagement: 3,
    mediumEngagement: 1,
    lowEngagement: 1,
    ltv: 970,
  },
  payments: {
    overdue: 1,
    overdueTotal: 150,
    overdueList: [
      {
        id: '3',
        client: 'Jennifer Lee',
        amount: 150,
        createdAt: new Date('2024-11-05'),
      },
    ],
  },
  sessions: {
    thisWeek: 12,
    completed: 8,
    utilization: 66.7,
  },
  churn: {
    rate: 3.2,
    previousRate: 4.0,
  },
  subscription: {
    active: true,
    plan: 'Pro Annual',
    endsAt: new Date('2025-11-19'),
  },
  needsSetup: false,
}

